### ISSUE TITLE
Update Proposal Submission Link

### ISSUE THREAD

**Issue by 1papaya** [hotosm/hot-summit-2020#10]
/call-for-proposals links to defunct 2019 proposal submission form. Update for 2020

**Comment by vannicer** [comment]
@jessbeutler working on this, will send link through

**Comment by BenDills** [comment]
Will add link when it is available.

**Comment by vannicer** [comment]
http://www.hotosm.org/updates/hot-summit-2020-call-for-sessions preferred; direct form link here- https://docs.google.com/forms/d/e/1FAIpQLSdCKnNVcKjDA8H6LtwegBbXuLF9lgjgt3ZgT7mTRoOj73hGVg/viewform
